openapi: 3.0.3
info:
  title: Employer Management API
  version: 1.0.0
  description: A simple Employer Management with JWT authentication
paths:
  /api/auth/login/:
    post:
      operationId: auth_login_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserLogin'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserLogin'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLogin'
          description: ''
  /api/auth/profile/:
    get:
      operationId: auth_profile_retrieve
      tags:
      - auth
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/auth/signup/:
    post:
      operationId: auth_signup_create
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRegistration'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserRegistration'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegistration'
          description: ''
  /api/employers/:
    get:
      operationId: employers_list
      tags:
      - employers
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employer'
          description: ''
    post:
      operationId: employers_create
      tags:
      - employers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Employer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Employer'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employer'
          description: ''
  /api/employers/{id}/:
    get:
      operationId: employers_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - employers
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employer'
          description: ''
    put:
      operationId: employers_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - employers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Employer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Employer'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employer'
          description: ''
    patch:
      operationId: employers_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - employers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedEmployer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedEmployer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedEmployer'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employer'
          description: ''
    delete:
      operationId: employers_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - employers
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    Employer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        company_name:
          type: string
          maxLength: 100
        contact_person_name:
          type: string
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 254
        phone_number:
          type: string
          maxLength: 20
        address:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        user:
          type: integer
          readOnly: true
      required:
      - address
      - company_name
      - contact_person_name
      - created_at
      - email
      - id
      - phone_number
      - user
    PatchedEmployer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        company_name:
          type: string
          maxLength: 100
        contact_person_name:
          type: string
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 254
        phone_number:
          type: string
          maxLength: 20
        address:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        user:
          type: integer
          readOnly: true
    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
    UserRegistration:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 100
        password1:
          type: string
          writeOnly: true
        password2:
          type: string
          writeOnly: true
      required:
      - email
      - id
      - password1
      - password2
      - username
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
